### ISSUE TITLE
Custom keyboard does not show when axis argument is provided (iOS 16+)

### ISSUE THREAD

**Issue by fraune** [paescebu/CustomKeyboardKit#15]
Hello there! First off, thanks for your work on this package :)

I've been poking around with the library, and have found that when supplying the [axis](https://developer.apple.com/documentation/swiftui/textfield/init(_:text:axis:)-7n1bm) argument to a `TextField`, the custom keyboard no longer shows, falling back on the standard keyboard.

I created a repo which should clearly demonstrate the issue: https://github.com/fraune/CustomKeyboardKit_TextFieldAxis_BugDemo

I forked this repo to see if I could figure it out myself, but I don't have as much experience with introspect. I'd love to hear if you have some thoughts on how we can work through this issue.

Cheers,
–Fraune

**Comment by paescebu** [comment]
Hey @fraune,

Thanks for the feedback, much appreciated, especially for the small example app, that accelerated my investigation!
That now lead to some optimizations in the Interface of CustomKeyboardKit for simpler use of it for you and for other integrators! :-) 

**To quickly explain the root cause:** 
It seems that as soon as you add the axis parameter SwiftUI creates a UITextArea under the hood instead of UITextField, causing the introspection to fail to find the right TextView. 
Additionally my implementation was limiting that if you use the `customKeyboard`modifier on `TextField` that it expected a UITextField, and for a `TextEditor` it expected a `UITextArea`, where the reality (as your case showed) is different. CustomKeyboardKit should now be smarter more straight forward for it.

I just updated CustomKeyboardKit to 1.0.2. This should resolve your issue I think.
let me know if it does!

Thank you so much for your time and a great weekend
Pascal

**Comment by fraune** [comment]
My guy. Quickest resolution ever! Thanks for the explanation as well.

Yep, confirming the update worked for my the demo project and my other project.

**Comment by paescebu** [comment]
Very glad to hear!

Have a great one. Ill close the ticket then.
