### ISSUE TITLE
Possibility to "relax" exact version of swiftui-introspect library?

### ISSUE THREAD

**Issue by xzilja** [paescebu/CustomKeyboardKit#16]
Started using CustomKeyboardKit today and it's a really pleasant library to work with! I was wondering if you would be open to possibility of relaxing version requirement of `swiftui-introspect` dependency from `exact` to "next major" or at least "next minor"?

Mainly, working in a project right now that uses latest version of this dependency `1.1.3` so it would be nice to share between libraries.

Alternatively, would you be open / what would it take to completely remove dependency on `swiftui-introspect`? If this is a viable idea, I'd be down to having a stab at this, with some help (i.e. bullet points of what needs to be done).

**Comment by paescebu** [comment]
@xzilja Hi!
Thanks for the positive feedback!
I think you're right. The version requirement for the dependency is something I haven't thought about much yet.

And indeed I'd be happy to help and relax the requirement.  Introspect is as far as I can tell following semantic versioning very well. So I'd feel perfectly comfortable to use the "up to next major" rule.

Feel free to issue a Pull Request.
Otherwise I will apply the change myself in the next few days.

Thank you very much for the suggestion!

Kind regards
Pascal

**Comment by paescebu** [comment]
Fixed in 1.0.4
