### ISSUE TITLE
Add onDismiss callback when keyboard dismissed

### ISSUE THREAD

**Issue by amoshsueh** [paescebu/CustomKeyboardKit#8]
Thanks for your hard work on this library, it's really useful!

I wonder if you can add an `onDismiss` callback when custom keyboard dismissed? 

When I click on other text fields (with default keyboard) while typing with custom keyboard, I need to handle something before dismissal and change the text.

Let me know if you need more details, thanks.

**Comment by paescebu** [comment]
Question:
What do you need in particular: 
A callback when keybords dismiss in general? or when you particular custom keyboard dismisses? 
Like, imagine you have multiple ones, would you want that all of those have separate callbacks?

**Comment by amoshsueh** [comment]
@paescebu Thanks for your quickly reply.

I want the particular custom keyboard which is in editing mode to have this dismiss callback. After all, only one text field can be edited at a time.

**Comment by paescebu** [comment]
@amoshsueh could you check out the branch`feature/add-editing-ended-callback` and tell me if this is what you imagined?
it's used:
SwiftUI: using a new modifier called: `onEditingChangedCustomKeyboard(action:)`
UIKit: assigning the CustomKeyboard the onEditingChanged closure

For your second question: No there is nothing yet. 

But i'm having second thoughts about this feature, i'll give you more insights after i got your feedback :)

**Comment by amoshsueh** [comment]
@paescebu  It doesn't seem to be working. I don't know if I'm missing something.

Code example:

```
let numberPad = CustomKeyboard.numberPad
numberPad.onEditingEnded = {
    print("onEditingEnded")  //  Nothing happened here
}
                
textField.inputView = numberPad.keyboardInputView
```

```
static var numberPad: CustomKeyboard {
    CustomKeyboardBuilder { textDocumentProxy, submit, playSystemFeedback in
         return VStack {
             // custom keyboard codes
         }
         .onEditingEndedCustomKeyboard {
             print("onEditingEnded") //  Nothing happened here
         }
    }
}
```

**Comment by paescebu** [comment]
make sure you use the `onEditingEndedCustomKeyboard`modifer the same way as the `onSubmitCustomKeyboard` modifier in the README.md. When in SwiftUI (from outside the Keyboard) and after the use of the `customKeyboard`modifier.

For UIKit i actually haven't tested it, yet and i guess to make it work there i have to change it up a bit :D 


**But ANYWAY, about my second thoughts:**

I like to be inspired by the default keyboards and APIs from Apple (on iOS), like in Messages, Contacts etc.
- There we also don't have a dismiss button and therefore a programmatic dismiss API directly.
- Also for native keyboards we also don't have callbacks when the keyboard dismisses, but in order to achieve what you want, we'd use the `FocusState` property wrappers for example and observe it's changes. I think that would be the best way also for CustomKeyboard and that should work out of the box. 
- To dismiss the keyboard programmatically, theres also no native API for it, but as well, we can set the focus State i assume, or call: `endEditing(true)` or `resignFirstResponder()` on the textField in UIKit, or call `UIApplication.shared.sendAction(#selector(UIResponder.resignFirstResponder), to: nil, from: nil, for: nil)` from anywhere.


What do you think? Does it make sense what I'm saying?

**Comment by amoshsueh** [comment]
@paescebu 

I use my own custom text field created by UIViewRepresentable and apply `onEditingEnded` but it's not working. Then I use SwiftUI's TextField and it's working perfectly. Maybe something wrong with my codes but it's fine.

I've been doing some thinking on my own, I should use this library in a different way.  The below API of TextField already meets my needs:

`public init<S>(_ title: S, text: Binding<String>, onEditingChanged: @escaping (Bool) -> Void) where S : StringProtocol`

So I think maybe there is no need for `onEditingEndedCustomKeyboard`. You can think about whether it is necessary to add this feature to the main branch.

I'm glad the discussion with you gave me some inspiration and thank you for being willing to share your thoughts with me.

Best wish.

**Comment by paescebu** [comment]
@amoshsueh 
True! Completely forgot that TextField also has a closure for that already!

Awesome to hear that my thoughts inspired to think the need through :)

Have a great one!
